core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
                  url('admin/', admin.site.urls),
                  url('', include(('mainweb.urls', 'mainweb'), namespace="mainweb")),
                  url('account/', include(('userdashboard.urls', 'account'), namespace="account")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainweb/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', MainWebIndexView.as_view(), name="Index"),
    path('register/', MainWebUserSignup.as_view(), name="UserRegister"),
    path('login/', MainWebLoginView.as_view(), name="UserLogin"),
    path('my-posts/', MainWebPostsView.as_view(), name="UserPostsView"),
    path('create/post/', MainWebCreatePost.as_view(), name="UserCreatePostView"),
    path('edit/post/<int:post_id>/', MainWebEditDeletePost.as_view(), name="UserEditDeletePostView"),
    path('all-posts/', MainWebGetAllPostsView.as_view(), name="AllPostsView"),
    path('post/<int:post_id>', MainWebGetPost.as_view(), name="GetPostView"),
    path('my-contacts/', MainWebContactView.as_view(), name="ContactView"),
    path('logout/', MainWebLogoutView.as_view(), name="LogoutView"),
    path('search/', MainWebSearchView.as_view(), name="SearchView"),
]

mainweb/models.py
from django.contrib.auth.models import User
from django.db import models

from django.utils.safestring import mark_safe

from userdashboard.choices import USER_POST_CHOICES, LOOKING_FOR_CHOICES, MOVE_IN_CHOICES, HOUSING_TYPE_CHOICES


class UserRegistration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    university = models.CharField(max_length=255)
    classification = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username


class UserPosts(models.Model):
    user_reg = models.ForeignKey(UserRegistration, on_delete=models.CASCADE, null=True, blank=True)
    role = models.CharField(max_length=20, null=True, blank=True, choices=USER_POST_CHOICES, default='AVAILABLE')
    looking_for = models.CharField(max_length=20, choices=LOOKING_FOR_CHOICES, null=True, blank=True)
    move_in = models.CharField(max_length=20, choices=MOVE_IN_CHOICES, null=True, blank=True)
    housing_type = models.CharField(max_length=12, choices=HOUSING_TYPE_CHOICES, null=True, blank=True)
    date = models.DateField()
    no_of_bedrooms = models.IntegerField(null=True, blank=True)
    no_of_bathrooms = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.user_reg.user.username


class ImageModel(models.Model):
    main_image = models.ImageField(upload_to='images/', null=True)
    image = models.ForeignKey(UserPosts, on_delete=models.CASCADE)

    def image_tag(self):
        if self.main_image:
            return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.main_image.url)
        else:
            return 'No Image Found'

    image_tag.short_description = 'Image'

    def __str__(self):
        return f'ID: {self.image.id} {self.image.user_reg.user.username} is looking for {self.image.looking_for}'

    def save(self, *args, **kwargs):
        try:
            this = ImageModel.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except:
            pass  # when new photo then we do nothing, normal case
        super().save(*args, **kwargs)


class UserContacts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.CharField(max_length=255)
    contacted_for = models.ForeignKey(UserPosts, on_delete=models.CASCADE)

    def __str__(self):
        return f'contacted {self.contacted_for.user_reg.user.username} for {self.contacted_for.looking_for}'

mainweb/views.py
from django import template
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.views import APIView

from mainweb.models import UserPosts, UserRegistration, ImageModel, UserContacts
from userdashboard.models import ApplicationUsers


class MainWebIndexView(View):

    def get(self, request):
        # Get only latest 3 posts for index page
        users_posts = UserPosts.objects.all()[:3]
        return render(request, 'main-web/pages/index.html', context={"users_posts": users_posts})


class MainWebLoginView(View):
    def get(self, request):
        return render(request, 'main-web/pages/user-login.html')

    def post(self, request):
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            return redirect('mainweb:UserPostsView')
        else:
            return render(request, 'main-web/pages/user-login.html', context={"error": "Invalid Credentials."})


class MainWebLogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        return redirect('mainweb:Index')


class MainWebUserSignup(View):

    def get(self, request):
        all_uni = ApplicationUsers.objects.all().values('university')
        return render(request, 'main-web/pages/user-signup.html', context={'universities': all_uni})

    def post(self, request):
        try:
            user = User()
            user.username = request.POST.get('username')
            user.set_password(request.POST.get('password'))
            user.email = request.POST.get('email')
            user.save()
            if user:
                UserRegistration.objects.create(user_id=user.id, age=request.POST.get('age'),
                                                gender=request.POST.get('gender'),
                                                university=request.POST.get('university'),
                                                classification=request.POST.get('classification'))
                login(request, user)
                return redirect('mainweb:UserPostsView')
            return render(request, 'main-web/pages/user-signup.html', context={'error': 'Error creating user'})
        except Exception as e:
            return render(request, 'main-web/pages/user-signup.html', context={'error': str(e)})


class MainWebGetAllPostsView(View):
    """Get all posts i.e(even when user is logged In, he wants to see all posts)"""

    def get(self, request):
        posts_list = UserPosts.objects.all()
        page = request.GET.get('page', 1)
        # by default only six posts will be rendered
        paginator = Paginator(posts_list, 6)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        return render(request, 'main-web/pages/all-posts.html', {'all_posts': posts})


class MainWebPostsView(View):
    """Get post against specific username"""

    def get(self, request):
        posts_list = UserPosts.objects.filter(user_reg__user__username=request.user.username)
        page = request.GET.get('page', 1)
        # by default only six posts will be rendered
        paginator = Paginator(posts_list, 6)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        return render(request, 'main-web/pages/user-posts.html', {'all_posts': posts})


class MainWebGetPost(View):

    def get(self, request, *args, **kwargs):
        """ GET specific post """
        try:
            post_obj = UserPosts.objects.get(id=kwargs.get("post_id"))
            posts_images = ImageModel.objects.filter(image__id=kwargs.get("post_id"))
            if request.GET.get('edit'):
                return render(request, 'main-web/pages/user-edit-post.html',
                              context={'data': post_obj, 'posts_images': posts_images})
            return render(request, 'main-web/pages/post-single.html',
                          context={'data': post_obj, 'posts_images': posts_images})
        except UserPosts.DoesNotExist:
            return HttpResponse("PostID not found", status=404)


class MainWebCreatePost(View):
    def get(self, request):
        all_uni = UserRegistration.objects.all().values('university')
        return render(request, 'main-web/pages/user-create-post.html', context={'universities': all_uni})

    def post(self, request, *args):
        """ Create post for requested user """
        post_created = UserPosts.objects.create(
            user_reg_id=request.user.userregistration_set.get(user_id=request.user.id).id,
            looking_for=request.POST.get('looking_for'), move_in=request.POST.get('move_in'),
            housing_type=request.POST.get('housing_type'), date=request.POST.get('date'),
            no_of_bedrooms=request.POST.get('no_bedrooms') if request.POST.get('no_bedrooms') else 0,
            no_of_bathrooms=request.POST.get('no_bathrooms') if request.POST.get('no_bathrooms') else 0)

        if post_created and request.POST.get('looking_for') == 'ROOMMATES':
            if request.FILES:
                for image in request.FILES.getlist('pics'):
                    ImageModel.objects.create(image_id=post_created.id, main_image=image)
                return redirect('mainweb:UserPostsView')
            return render(request, 'main-web/pages/user-create-post.html', context={'error': 'Error creating post'})
        else:
            return redirect('mainweb:UserPostsView')


class MainWebEditDeletePost(APIView):
    """ Edit/Delete specific post"""

    def get(self, request, *args, **kwargs):
        try:
            UserPosts.objects.get(id=kwargs.get('post_id')).delete()
            return redirect('mainweb:UserPostsView')
        except ObjectDoesNotExist:
            return render(request, 'main-web/pages/user-edit-post.html', context={"error": "ID not found"})

    def post(self, request, *args, **kwargs):
        try:
            post_obj = UserPosts.objects.get(id=kwargs.get('post_id'))
            post_obj.looking_for = request.POST.get('looking_for')
            post_obj.role = request.POST.get('status')
            post_obj.move_in = request.POST.get('move_in')
            post_obj.housing_type = request.POST.get('housing_type')
            post_obj.date = request.POST.get('date')
            post_obj.no_of_bedrooms = request.POST.get('no_bedrooms') if request.POST.get('no_bedrooms') else 0
            post_obj.no_of_bathrooms = request.POST.get('no_bathrooms') if request.POST.get('no_bathrooms') else 0
            post_obj.save()
            if post_obj and request.POST.get('looking_for') == 'ROOMMATES':
                if request.FILES:
                    for image in request.FILES.getlist('pics'):
                        img_obj = ImageModel()
                        img_obj.image_id = post_obj.id
                        img_obj.main_image = image
                        img_obj.save()
                    return redirect('mainweb:UserPostsView')
                else:
                    return redirect('mainweb:UserPostsView')
            else:
                return redirect('mainweb:UserPostsView')
        except Exception as e:
            return render(request, 'main-web/pages/user-edit-post.html', context={'error': str(e)})


class MainWebContactView(View):

    def get(self, request):
        contacts = UserContacts.objects.filter(user=request.user)
        return render(request, 'main-web/pages/user-contacts.html', context={'contacts': contacts})

    def post(self, request):
        # TODO once get SMTP-credentials rest of the work needs to be done here
        message = request.POST.get('message', None)
        post_id = request.POST.get('post_id', None)
        try:
            post_obj = UserPosts.objects.get(id=post_id)
            UserContacts.objects.create(user=request.user, message=message, contacted_for=post_obj)
            return redirect('mainweb:ContactView')
        except ObjectDoesNotExist:
            return HttpResponse('Error contacting!')


class MainWebSearchView(View):

    def post(self, request, *args, **kwargs):
        gender = request.POST.get('gender', None)
        move_in = request.POST.get('move_in', None)
        university = request.POST.get('university', None)
        posts_list = []
        if gender:
            posts_list = UserPosts.objects.filter(user_reg__gender=gender)
        if move_in:
            posts_list = UserPosts.objects.filter(date__exact=move_in)
        if university:
            posts_list = UserPosts.objects.filter(user_reg__university=university)
        if gender and move_in:
            posts_list = UserPosts.objects.filter(Q(date__exact=move_in) & Q(user_reg__gender=gender))
        if gender and university:
            posts_list = UserPosts.objects.filter(Q(user_reg__university=university) & Q(user_reg__gender=gender))
        if move_in and university:
            posts_list = UserPosts.objects.filter(Q(user_reg__university=university) & Q(date__exact=move_in))
        if gender and move_in and university:
            posts_list = UserPosts.objects.filter(
                Q(user_reg__university=university) & Q(date__exact=move_in) & Q(user_reg__gender=gender))

        page = request.GET.get('page', 1)
        # by default only six posts will be rendered
        paginator = Paginator(posts_list, 6)

templates/main-web/pages/all-posts.html
{% extends "main-web/base.html" %}
{% block title %} RoommateApp | All Posts {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main id="main">

        <!-- ======= Intro Single ======= -->
        <section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box">
                            <h1 class="title-single">All Posts</h1>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        {% if user.is_authenticated %}
                            <a href="/create/post/" class="btn btn-b">Add Post</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section><!-- End Intro Single-->

        <!-- ======= Property Grid ======= -->
        <section class="property-grid grid">
            <div class="container">
                {% if all_posts %}
                    <div class="row">
                        {% for post in all_posts %}
                            <div class="col-md-4">
                                <div class="card-box-a card-shadow">
                                    <div class="img-box-a">
                                        <img src="/static/main-website/assets/img/property-1.jpg" alt=""
                                             class="img-a img-fluid">
                                    </div>
                                    <div class="card-overlay">
                                        <div class="card-overlay-a-content">
                                            <div class="card-header-a">
                                                <h6 class="card-title-a">
                                                    <b>Looking for: </b>{{ post.looking_for }}
                                                </h6>
                                            </div>
                                            <div class="card-body-a">
                                                <a href="{% url 'mainweb:GetPostView' post.id %}" class="link-a">Click
                                                    here
                                                    to view
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <nav class="pagination-a">
                                {% if all_posts.has_other_pages %}
                                    <ul class="pagination justify-content-end">
                                        {% if all_posts.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ all_posts.previous_page_number }}"
                                                   tabindex="-1">
                                                    <span class="bi bi-chevron-left"></span>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1">
                                                    <span class="bi bi-chevron-left"></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for i in all_posts.paginator.page_range %}
                                            {% if all_posts.number == i %}
                                                <li class="page-item active">
                                                    <a class="page-link" href="#">{{ i }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link"
                                                                         href="?page={{ i }}">{{ i }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if all_posts.has_next %}
                                            <li class="page-item next">
                                                <a class="page-link" href="?page={{ all_posts.next_page_number }}">
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1">
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}

                            </nav>
                        </div>
                    </div>
                {% else %}
                    <div class="row">
                        <h4>No Posts Added.</h4>
                    </div>
                {% endif %}

            </div>
        </section><!-- End Property Grid Single-->

    </main><!-- End #main -->
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/main-web/pages/user-contacts.html
{% extends "main-web/base.html" %}
{% block title %} Roommate App | My Contacts {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main id="main">
        <!-- ======= Contact Single ======= -->
        <div class="container">
            <div class="row">
                <div class="col-md-12 section-t8">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-borderless">
                                    <thead>
                                    <tr>
                                        <th scope="col">Contacted For</th>
                                        <th scope="col">Message</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for contact in contacts %}
                                        <tr>
                                            <th scope="row"><a
                                                    href="/post/{{ contact.contacted_for.user_reg.id }}">{{ contact.contacted_for.looking_for }}</a>
                                            </th>
                                            <td>{{ contact.message }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Contact Single-->

    </main><!-- End #main -->
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

templates/main-web/pages/user-login.html
{% extends "main-web/base.html" %}
{% block title %} Login | Roommate Matching App {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main id="main">
        <!-- ======= Contact Single ======= -->
        <section class="vh-100">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card shadow-2-strong" style="border-radius: 1rem;">
                            <div class="card-body p-5">
                                <h3 class="mb-5">Sign in</h3>
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input type="text" name="username" class="form-control" id="floatingInput"
                                               placeholder="Username" required>
                                        <label for="floatingInput">Username</label>
                                    </div>
                                    <div class="form-floating">
                                        <input type="password" name="password" class="form-control"
                                               id="floatingPassword"
                                               placeholder="Password" required>
                                        <label for="floatingPassword">Password</label>
                                    </div>
                                    {% if error %}
                                        <br>
                                        <p class="text-danger">{{ error }}</p>
                                    {% endif %}
                                    <br>
                                    <div class="col-md-12">
                                        <button class="btn btn-a" type="submit">Login</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End Contact Single-->

    </main><!-- End #main -->
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/main-web/pages/user-posts.html
{% extends "main-web/base.html" %}
{% block title %} RoommateApp | My Posts {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main id="main">

        <!-- ======= Intro Single ======= -->
        <section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box">
                            <h1 class="title-single">My Posts</h1>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        <a href="/create/post/" class="btn btn-b">Add Post</a>
                    </div>
                </div>
            </div>
        </section><!-- End Intro Single-->

        <!-- ======= Property Grid ======= -->
        <section class="property-grid grid">
            <div class="container">
                {% if all_posts %}
                    <div class="row">
                        {% for post in all_posts %}
                            <div class="col-md-4">
                                <div class="card-box-a card-shadow">
                                    <div class="img-box-a">
                                        <img src="/static/main-website/assets/img/property-1.jpg" alt=""
                                             class="img-a img-fluid">
                                    </div>
                                    <div class="card-overlay">
                                        <div class="card-overlay-a-content">
                                            <div class="card-header-a">
                                                <h6 class="card-title-a">
                                                    <b>Looking For: </b> {{ post.looking_for }}
                                                </h6>
                                            </div>
                                            <div class="card-body-a">
                                                <a href="{% url 'mainweb:GetPostView' post.id %}" class="link-a">Click
                                                    here
                                                    to view
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <nav class="pagination-a">
                                {% if all_posts.has_other_pages %}
                                    <ul class="pagination justify-content-end">
                                        {% if all_posts.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ all_posts.previous_page_number }}"
                                                   tabindex="-1">
                                                    <span class="bi bi-chevron-left"></span>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1">
                                                    <span class="bi bi-chevron-left"></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for i in all_posts.paginator.page_range %}
                                            {% if all_posts.number == i %}
                                                <li class="page-item active">
                                                    <a class="page-link" href="#">{{ i }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link"
                                                                         href="?page={{ i }}">{{ i }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if all_posts.has_next %}
                                            <li class="page-item next">
                                                <a class="page-link" href="?page={{ all_posts.next_page_number }}">
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="page-item disabled">
                                                <a class="page-link" href="#" tabindex="-1">
                                                    <span class="bi bi-chevron-right"></span>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}

                            </nav>
                        </div>
                    </div>
                {% else %}
                    <div class="row">
                        <h4>No Posts Added.</h4>
                    </div>
                {% endif %}

            </div>
        </section><!-- End Property Grid Single-->

    </main><!-- End #main -->
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}